### ISSUE TITLE
Image on the buttons Keyboard_delete and Keyboard doesnt show

### ISSUE THREAD

**Issue by bergetun** [mmachado53/SimpleSwiftNumericKeyboard#4]
First of all. Thanks for a great library. 

There seems to be a bug with two of the buttons. 
Even though i have added the keyboard_delete_icon and keyboard_hide_icons to my assest the images on these two buttons doesnt show when the keyboard pops up.

**Comment by mmachado53** [comment]
thanks, i will work on it today !

**Comment by mmachado53** [comment]
The issue is fixed, please update to 0.1.4 version :)
